import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>전진의 자기소개 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          <p>Hello, This is Jin.</p>
          <img className={styles.me_img} src = "/me.jpeg"> 
            </img>
        </h1>

        <div className={styles.grid}>
          <a href="https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=%EC%A0%84%EC%A7%84" 
            className={styles.card}>
            <img className={styles.info_img} src="/me.jpeg"></img>
            <p>Self Introduction</p>
            <p>
              <h2>Student of Handong Univ. 
              <br></br>
              Majoring in Linguistics / Computer Science
              <br></br>
              Interest lies on NLP, specifically on STT transition.
              <br></br>
              For contact, Please look below. 
              </h2>
            </p>
          </a>

          <a className={styles.card}>
            <img className={styles.info_img} src="/contact.jpg"></img>
            <p>
              Contact
            </p>
            <h2>
              E-mail : 21700645@handong.ac.kr  
              <br></br>
              phone : 010-6309-1142 
            </h2>
          </a>
          <a
            href="https://github.com/Onseted"
            className={styles.card}
          >
            <img className={styles.info_img} src="/code.jpg"></img>
            <p>Git Repository as Developer</p>
            <h2> Click this card to move Jin`s Repository. </h2>
          </a>
        </div>
      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Footer Copywrite autorized from VERCEL
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
