import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'

const MeImg = styled(Image)`
  width: 35%;
  height:50%;
`; 

const CardImg = styled(Image)`
  text-align: center; 
  border-radius: 10px;
`; 

const Jmain = styled.main`
  min-height: 100vh;
  padding: 2rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: black;
  color: #dfc7d5;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Introduction of Jin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Jmain>
        <h1 className={styles.title}>
          <p>Hello, This is Jin.</p>
          <MeImg 
            src="/me.jpg"
            width = {300}
            height = {400} 
          />
        </h1>

        <div className={styles.grid}>
          <a href="https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=%EC%A0%84%EC%A7%84" 
            className={styles.card}>
            <MeImg 
              src="/intro.jpg"
              width = {50}
              height = {50} 
            />
            <h2>Self Introduction</h2>
            <p>
              Student of Handong Univ. 
              <br></br>
              Interest lies in NLP(STT).
            </p>
          </a>

          <a className={styles.card}>
            <MeImg 
              src="/contact.jpg"
              width = {50}
              height = {50} 
            />
            <h2>
              Contact
            </h2>
            <p>
              E-mail : 21700645@handong.ac.kr  
              <br></br>
              phone : 010-6309-1142 
            </p>
          </a>
          <a
            href="https://github.com/Onseted"
            className={styles.card}
          >
            <MeImg 
              src="/code.jpg"
              width = {50}
              height = {50} 
            />
            <h2>Git Repository as Developer</h2>
            <p> Click this card to move Jin`s Repository. </p>
          </a>
        </div>
      </Jmain>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copywrite : VERCEL
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
/*<img className={styles.me_img} src = "/me.jpg"> 
            </img>*/ 
